site_name: IBM CloudÂ® for Partners
nav:
  - Home: 
    - Home page: index.md
    - Financial Services Cloud: ./financial-services.md
    - About: about.md
  - IaaS:
    - Cloud Native:
      - Cloud Object Storage: ./cloud/storage.md
      - Virtual Private Clouds (VPC) in the Public Cloud: ./cloud/vpc.md
      - VPC Architectures: ./cloud/vpc-architecture.md
    - Extended enterprise:
      - PowerVS: ./cloud/powervs.md
      - Deploy PowerVS: ./cloud/powervs-vpc.md
    - Bare Metal Servers: 
      - Overview: ./cloud/baremetal.md
      - Bare Metal Classic: ./cloud/baremetal-classic.md
      - Bare Metal VPC: ./cloud/baremetal-vpc.md
      - Transit Gateway: ./cloud/transitgateway.md
    - VWware on IBM Cloud:
      - VMware offerings: ./cloud/vmware.md
      - VMware as a Service on Bare Metal: ./cloud/vmware-as-a-service.md
      - Bare Metal Classic for VMware: ./cloud/baremetal-vmware.md
      - VMware on Virtual Private Cloud (VPC): ./cloud/baremetal-vpc-vmware.md
  - PaaS:
    - Key and Hyper Protect Services:
      - Key Protect: ./security/keyprotect.md
      - Key Protect tutorials: ./security/keyprotect-tutorials.md
      - Hyper Protect Crypto Services: ./security/hyperprotect.md
      - Hyper Protect tutorials: ./security/hyperprotect-tutorials.md
      - Unified Key: ./security/unifiedkey.md
extra_css:
  - stylesheets/extra.css
theme: 
  name: material
  font:
      text: Nanum Gothic
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.share
  language: en
  icon: 
      repo: fontawesome/brands/github
      edit: material/pencil 
      view: material/eye
  logo: ./media/R.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      lang: en
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.smartsymbols
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2023 IBM | However, all opinions and views are my own 
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/brucedkyle
    - icon: fontawesome/brands/github
      link: https://github.com/brucedkyle/
    - icon: fontawesome/solid/envelope
      link: mailto:bruce.kyle@ibm.com
repo_url: https://github.com/brucedkyle/ibmcloud_for_isvs
repo_name: brucedkyle/ibmcloud_for_isvs
edit_uri: edit/main/docs/